metros = float(input('Digite uma distancia em metros: '))
print('A medida de {}m corresponde a:'.format(metros))
print(metros/1000,'km')
print(metros/100,'hm')
print(metros/10,'dam')
print('{:.0f}dm'.format(metros*10))
print('{:.0f}cm'.format(metros*100))
print('{:.0f}mm'.format(metros*1000))